### ISSUE TITLE
「頁面」有發佈日期(meta__time)；上一篇、下一篇(article__pagenav)

### ISSUE THREAD

**Issue by andyli0123** [teacat/tunalog#1]
![image](https://user-images.githubusercontent.com/21230214/73253217-0b44b080-41f7-11ea-9f72-edaf4609c48f.png)

1. 頁面有「meta__time」和「article__pagenav」，建議刪除。
2. 希望改成下拉式選單，並於首頁上方顯示。

**Comment by YamiOdymel** [comment]
第一點的話應該是可以捏成選項在佈景主題設置的地方更改（因為我還真忘記有單頁頁面這回事了），第二點的話我不太懂是什麼意思。

什麼東西希望可以改成下拉式選單？

**Comment by andyli0123** [comment]
https://i.imgur.com/11el8kX.png
目前的選單不太好看，而且還多了一條捲動軸。
希望改成「下拉式選單」，如：https://i.imgur.com/pB4cAZ3.mp4

**Comment by YamiOdymel** [comment]
側邊欄的設計其實原本是用來藏「登入」或者是一些偏向讓管理員用的功能，當側邊欄沒有任何工具的時候「選單」按鈕也就會自動消失。

這樣的話看來是要額外想個辦法在首頁搞個「單頁頁面下拉式選單」了

**Comment by YamiOdymel** [comment]
稍微更新一下進度，下拉式選單會以純 CSS 實作，所以不會支援雙層選單，多層選單會被整併到同一排。外觀上還有一些小 Bug 沒有修繕、最終外觀應該不會跟這個差太遠…。

![image](https://user-images.githubusercontent.com/7308718/73356084-7dd78e00-42d4-11ea-97cd-e05d0fbe6715.png)

![image](https://user-images.githubusercontent.com/7308718/73356211-c8f1a100-42d4-11ea-8bad-cf05223f730a.png)

**Comment by YamiOdymel** [comment]
完成於 4d42897fdadf1020ea7b854f5a74005b889a5e63
