### ISSUE TITLE
首頁的連結預覽圖是 assets\images\16-9.png

### ISSUE THREAD

**Issue by andyli0123** [teacat/tunalog#2]
![image](https://user-images.githubusercontent.com/21230214/73518182-952f8c00-4438-11ea-8877-eb6160bbd038.png)

首頁的連結預覽圖是 assets\images\16-9.png，這是正常的嗎？

**Comment by YamiOdymel** [comment]
這個設計是預期的，因為佈景主題沒有預設預覽圖或是自訂首頁特色圖片的功能
