### ISSUE TITLE
在 Firefox 瀏覽器的頁腳顯示問題

### ISSUE THREAD

**Issue by andyli0123** [teacat/tunalog#3]
![image](https://user-images.githubusercontent.com/21230214/73545524-6e904600-4476-11ea-9884-0fe82b1dccd2.png)

**Comment by YamiOdymel** [comment]
Firefox 的輸入欄位設計有預設最小寬度，導致無法更小（[Strange input widths in Firefox vs. Chrome](https://stackoverflow.com/questions/43314921/strange-input-widths-in-firefox-vs-chrome)）。

將輸入欄位指定 `min-width: 0;` 覆寫允許的最小寬度就修好了。這幾年越來越會被 Firefox 坑，快跟 IE 搶第一名了

**Comment by andyli0123** [comment]
話說用 Internet Explorer 瀏覽器來看，有點恐怖。(雖然已經很少人用了)

**Comment by YamiOdymel** [comment]
真要支援 Internet Explorer 我就會寫一個純文字的仿終端機佈景主題，因為只有純文字才不會讓 IE 錯位
